INSERT INTO actors (firstname, lastname, bio, rating) VALUES
('Robert', 'De Niro', 'American actor known for intense portrayals in ''Taxi Driver'', ''Raging Bull'', and ''Goodfellas''.', 9.5),
('Al', 'Pacino', 'American actor acclaimed for roles in ''The Godfather'', ''Scarface'', and ''Heat''.', 9.4),
('Meryl', 'Streep', 'American actress and three-time Oscar winner known for ''Sophie''s Choice'' and ''The Iron Lady''.', 9.6),
('Leonardo', 'DiCaprio', 'American actor and producer known for ''Inception'', ''Titanic'', and ''The Revenant''.', 9.3),
('Tom', 'Hanks', 'American actor and two-time Oscar winner known for ''Forrest Gump'' and ''Saving Private Ryan''.', 9.2),
('Denzel', 'Washington', 'American actor celebrated for performances in ''Training Day'' and ''Malcolm X''.', 9.1),
('Cate', 'Blanchett', 'Australian actress and two-time Oscar winner known for ''Blue Jasmine'' and ''Elizabeth: The Golden Age''.', 8.9),
('Morgan', 'Freeman', 'American actor and Oscar winner known for ''Shawshank Redemption'' and ''Million Dollar Baby''.', 9.0),
('Jack', 'Nicholson', 'American actor three-time Oscar winner known for ''One Flew Over the Cuckoo''s Nest'' and ''As Good as It Gets''.', 9.2),
('Natalie', 'Portman', 'Israeli-American actress and Oscar winner known for ''Black Swan'' and ''V for Vendetta''.', 8.8),
('Brad', 'Pitt', 'American actor and producer known for ''Fight Club'', ''Once Upon a Time in Hollywood'', and ''Se7en''.', 8.9),
('Angelina', 'Jolie', 'American actress and Oscar winner known for ''Girl, Interrupted'' and ''Maleficent''.', 8.7),
('Anthony', 'Hopkins', 'Welsh actor and two-time Oscar winner known for ''The Silence of the Lambs'' and ''The Remains of the Day''.', 9.0),
('Joaquin', 'Phoenix', 'American actor and Oscar winner known for ''Joker'' and ''Gladiator''.', 8.8),
('Kate', 'Winslet', 'British actress and Oscar winner known for ''Titanic'' and ''The Reader''.', 8.9),
('Christian', 'Bale', 'British actor and Oscar winner known for ''American Psycho'' and ''The Dark Knight''.', 8.7),
('Emma', 'Stone', 'American actress and Oscar winner known for ''La La Land'' and ''The Favourite''.', 8.6),
('Matthew', 'McConaughey', 'American actor and Oscar winner known for ''Dallas Buyers Club'' and ''Interstellar''.', 8.5),
('Jennifer', 'Lawrence', 'American actress and Oscar winner known for ''Silver Linings Playbook'' and ''The Hunger Games''.', 8.4),
('Javier', 'Bardem', 'Spanish actor and Oscar winner known for ''No Country for Old Men'' and ''Biutiful''.', 8.5),
('Russell', 'Crowe', 'New Zealand actor and Oscar winner known for ''Gladiator'' and ''A Beautiful Mind''.', 8.6),
('Hilary', 'Swank', 'American actress and two-time Oscar winner known for ''Boys Don''t Cry'' and ''Million Dollar Baby''.', 8.4),
('Sean', 'Penn', 'American actor and two-time Oscar winner known for ''Mystic River'' and ''Milk''.', 8.7),
('Renée', 'Zellweger', 'American actress and two-time Oscar winner known for ''Chicago'' and ''Cold Mountain''.', 8.6),
('Emma', 'Thompson', 'British actress and Oscar winner known for ''Howards End'' and ''Sense and Sensibility''.', 8.3),
('Mahershala', 'Ali', 'American actor and two-time Oscar winner known for ''Moonlight'' and ''Green Book''.', 8.4),
('Tom', 'Cruise', 'American actor known for ''Top Gun'', ''Jerry Maguire'', and the ''Mission: Impossible'' series.', 8.2),
('Sally', 'Field', 'American actress and two-time Oscar winner known for ''Norma Rae'' and ''Places in the Heart''.', 8.1),
('Daniel', 'Day-Lewis', 'British actor and three-time Oscar winner known for ''There Will Be Blood'' and ''Lincoln''.', 9.0),
('Ingrid', 'Bergman', 'Swedish actress and three-time Oscar winner known for ''Casablanca'' and ''Notorious''.', 8.9),
('Christopher', 'Walken', 'American actor and Oscar winner known for ''The Deer Hunter'' and ''Catch Me If You Can''.', 8.2),
('Sean', 'Connery', 'Scottish actor and Oscar winner known for ''The Untouchables'' and ''Indiana Jones''.', 8.8),
('Michael', 'Caine', 'British actor and two-time Oscar winner known for ''The Cider House Rules'' and ''Hannah and Her Sisters''.', 8.3),
('Jodie', 'Foster', 'American actress and two-time Oscar winner known for ''The Accused'' and ''Silence of the Lambs''.', 8.3),
('Vivien', 'Leigh', 'British actress and two-time Oscar winner known for ''Gone with the Wind'' and ''A Streetcar Named Desire''.', 8.7),
('Sidney', 'Poitier', 'Bahamian-American actor and Oscar winner known for ''Lilies of the Field'' and ''Guess Who''.', 8.5),
('Halle', 'Berry', 'American actress and Oscar winner known for ''Monster''s Ball'' and ''Introducing Dorothy Dandridge''.', 7.9),
('Forest', 'Whitaker', 'American actor and Oscar winner known for ''The Last King of Scotland'' and ''Lee Daniels'' The Butler''.', 8.1),
('Marlon', 'Brando', 'American actor and two-time Oscar winner known for ''The Godfather'' and ''On the Waterfront''.', 9.4),
('Charlize', 'Theron', 'South African actress and Oscar winner known for ''Monster'' and ''North Country''.', 8.2),
('Nicole', 'Kidman', 'Australian actress and Oscar winner known for ''The Hours'' and ''Moulin Rouge!''.', 8.0),
('Jamie', 'Foxx', 'American actor and Oscar winner known for ''Ray'' and ''Django Unchained''.', 8.0),
('Gwyneth', 'Paltrow', 'American actress and Oscar winner known for ''Shakespeare in Love'' and ''The Royal Tenenbaums''.', 7.8),
('Kevin', 'Spacey', 'American actor and two-time Oscar winner known for ''American Beauty'' and ''The Usual Suspects''.', 8.0),
('Harrison', 'Ford', 'American actor known for ''Star Wars'', ''Blade Runner'', and the ''Indiana Jones'' series.''.', 8.4),
('Sigourney', 'Weaver', 'American actress known for ''Alien'' and ''Ghostbusters''.', 8.1),
('Samuel L.', 'Jackson', 'American actor known for ''Pulp Fiction'', ''Snakes on a Plane'', and ''The Avengers''.', 8.2),
('Keanu', 'Reeves', 'Canadian actor known for ''The Matrix'', ''John Wick'', and ''Speed''.', 8.0),
('Sylvester', 'Stallone', 'American actor known for ''Rocky'' and ''Rambo'' franchises.', 7.7),
('Jack', 'Black', 'American actor and musician known for ''School of Rock'' and ''Shallow Hal''.', 7.6),
('Adam', 'Sandler', 'American actor, comedian, and producer known for ''Happy Gilmore'' and ''The Wedding Singer''.', 7.5),
('Steve', 'Carell', 'American actor and comedian known for ''The 40-Year-Old Virgin'' and ''Foxcatcher''.', 7.8),
('Reese', 'Witherspoon', 'American actress and Oscar winner known for ''Walk the Line'' and ''Legally Blonde''.', 7.9),
('Olivia', 'Colman', 'British actress and Oscar winner known for ''The Favourite'' and ''The Crown''.', 8.3),
('Rami', 'Malek', 'American actor and Oscar winner known for ''Bohemian Rhapsody'' and ''Mr. Robot''.', 8.0),
('Chris', 'Hemsworth', 'Australian actor known for ''Thor'', ''Snow White and the Huntsman'', and ''Extraction''.', 7.8),
('Chris', 'Evans', 'American actor known for ''Captain America'', ''Snowpiercer'', and ''Knives Out''.', 7.9),
('Robert', 'Downey Jr.', 'American actor and producer known for ''Iron Man'' and ''Sherlock Holmes''.', 8.5),
('Scarlett', 'Johansson', 'American actress known for ''Lost in Translation'', ''Lucy'', and Marvel films.', 8.1),
('Mark', 'Ruffalo', 'American actor known for ''Spotlight'', ''Shutter Island'', and the ''Avengers'' franchise.''.', 7.7),
('Benedict', 'Cumberbatch', 'British actor known for ''The Imitation Game'', ''Doctor Strange'', and ''Sherlock''.', 8.0),
('Tom', 'Hardy', 'British actor known for ''Inception'', ''Mad Max: Fury Road'', and ''The Dark Knight Rises''.', 8.0),
('Robert', 'Redford', 'American actor and producer known for ''Butch Cassidy and the Sundance Kid'' and ''All the President''s Men''.', 8.2),
('Dustin', 'Hoffman', 'American actor and two-time Oscar winner known for ''Rain Man'' and ''Kramer vs. Kramer''.', 8.3),
('Shirley', 'MacLaine', 'American actress and Oscar winner known for ''Terms of Endearment'' and ''Steel Magnolias''.', 8.1),
('Michael', 'Douglas', 'American actor and two-time Oscar winner known for ''Wall Street'' and ''Fatal Attraction''.', 8.2),
('Jennifer', 'Connelly', 'American actress and Oscar winner known for ''A Beautiful Mind'' and ''Requiem for a Dream''.', 7.9),
('Benicio', 'Del Toro', 'Puerto Rican-American actor and Oscar winner known for ''Traffic'' and ''Guardians of the Galaxy''.', 7.8),
('Anne', 'Hathaway', 'American actress and Oscar winner known for ''Les Misérables'' and ''The Devil Wears Prada''.', 7.7),
('Lupita', 'Nyong''o', 'Kenyan-Mexican actress and Oscar winner known for ''12 Years a Slave'' and ''Black Panther''.', 7.6),
('Frances', 'McDormand', 'American actress and three-time Oscar winner known for ''Fargo'', ''Nomadland'', and ''Three Billboards Outside Ebbing, Missouri''.', 8.4),
('Michelle', 'Yeoh', 'Malaysian actress and Oscar winner known for ''Everything Everywhere All at Once'' and ''Crazy Rich Asians''.', 8.1),
('Keira', 'Knightley', 'British actress known for ''Pirates of the Caribbean'', ''Pride & Prejudice'', and ''Atonement''.', 7.8),
('Glenn', 'Close', 'American actress known for ''Fatal Attraction'', ''Dangerous Liaisons'', and ''Albert Nobbs''.', 8.0),
('Christoph', 'Waltz', 'Austrian-German actor and two-time Oscar winner known for ''Inglourious Basterds'' and ''Django Unchained''.', 8.2),
('Viola', 'Davis', 'American actress and Oscar winner known for ''Fences'', ''How to Get Away with Murder'', and ''The Help''.', 8.3),
('Philip', 'Seymour Hoffman', 'American actor and Oscar winner known for ''Capote'' and ''The Master''.', 8.1),
('Drew', 'Barrymore', 'American actress and producer known for ''E.T. the Extra-Terrestrial'' and ''50 First Dates''.', 7.2),
('Jim', 'Carrey', 'Canadian-American actor and comedian known for ''The Mask'', ''The Truman Show'', and ''Eternal Sunshine of the Spotless Mind''.', 8.0),
('Will', 'Smith', 'American actor and Oscar winner known for ''King Richard'' and ''The Pursuit of Happyness''.', 8.2),
('Eddie', 'Redmayne', 'British actor and Oscar winner known for ''The Theory of Everything'' and ''Fantastic Beasts''.', 7.8),
('Amy', 'Adams', 'American actress known for ''Arrival'', ''American Hustle'', and ''The Fighter''.', 7.9),
('Mark', 'Wahlberg', 'American actor and producer known for ''Boogie Nights'', ''The Departed'', and ''Ted''.', 7.6),
('Michael', 'Fassbender', 'German-Irish actor known for ''X-Men: First Class'', ''12 Years a Slave'', and ''Steve Jobs''.', 7.8),
('Helen', 'Mirren', 'British actress and Oscar winner known for ''The Queen'', ''The Last Station'', and ''Woman in Gold''.', 8.2),
('Jessica', 'Lange', 'American actress and two-time Tony Award winner known for ''Tootsie'' and ''Blue Sky''.', 8.0),
('Susan', 'Sarandon', 'American actress and Oscar winner known for ''Dead Man Walking'' and ''The Client''.', 7.9),
('James', 'Stewart', 'American actor and three-time Oscar winner known for ''The Philadelphia Story'', ''Rear Window'', and ''It''s a Wonderful Life''.', 8.1),
('Gary', 'Oldman', 'English actor and Oscar winner known for ''Tinker Tailor Soldier Spy'', ''Darkest Hour'', and ''Harry Potter''.', 8.3),
('Heath', 'Ledger', 'Australian actor and Oscar winner known for ''Brokeback Mountain'', ''The Dark Knight'', and ''A Knight''s Tale''.', 9.0),
('Robin', 'Williams', 'American actor and Oscar winner known for ''Good Will Hunting'', ''Mrs. Doubtfire'', and ''Dead Poets Society''.', 8.9),
('Vanessa', 'Redgrave', 'British actress and Oscar winner known for ''Julia'', ''Howards End'', and ''Shakespeare in Love''.', 7.9),
('Geoffrey', 'Rush', 'Australian actor and Oscar winner known for ''Shine'', ''The King''s Speech'', and ''Pirates of the Caribbean''.', 7.8),
('Ben', 'Kingsley', 'British actor and Oscar winner known for ''Gandhi'', ''Schindler''s List'', and ''Sexy Beast''.', 8.0),
('Emma', 'Watson', 'British actress and activist known for ''Harry Potter'' series and ''Beauty and the Beast''.', 7.5),
('Andy', 'Serkis', 'English actor and pioneer of motion capture known for Gollum in ''The Lord of the Rings'' and Caesar in ''Planet of the Apes''.', 7.6),
('Mark', 'Hamill', 'American actor and writer known for ''Star Wars'', ''Batman: The Animated Series'', and ''Hamill & Hardy''.', 7.7),
('Eva Marie', 'Saint', 'American actress and Oscar winner known for ''On the Waterfront'', ''Exodus'', and ''North by Northwest''.', 8.0),
('Christian', 'Slater', 'American actor and film producer known for ''Heathers'', ''True Romance'', and ''Interview with the Vampire''.', 7.4),
('Michelle', 'Pfeiffer', 'American actress and Oscar nominee known for ''Scarface'', ''Fatal Attraction'', and ''Batman Returns''.', 7.9);
