INSERT INTO movies (title, year, description, rating) VALUES
('The Shawshank Redemption', 1994, 'Two imprisoned men bond forging friendship and hope.', 9.3),
('The Godfather', 1972, 'The aging patriarch transfers control of his crime family.', 9.2),
('The Dark Knight', 2008, 'Batman faces the Joker who wants chaos in Gotham.', 9.0),
('The Godfather Part II', 1974, 'Continuing saga of the Corleone family with flashbacks.', 9.0),
('12 Angry Men', 1957, 'Jurors debate guilt in a tense courtroom drama.', 9.0),
('Schindler''s List', 1993, 'Oskar Schindler saves Jews during the Holocaust.', 8.9),
('The Lord of the Rings: The Return of the King', 2003, 'Final battle for Middle-earth''s fate.', 8.9),
('Pulp Fiction', 1994, 'Interwoven stories of crime in Los Angeles.', 8.9),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Hobbits begin a quest to destroy a ring.', 8.8),
('The Good, the Bad and the Ugly', 1966, 'Three gunslingers search for gold during the Civil War.', 8.8),
('Fight Club', 1999, 'An insomniac meets a soapmaker, starting an underground club.', 8.8),
('Forrest Gump', 1994, 'Man with low IQ witnesses key historical events.', 8.8),
('Inception', 2010, 'Thieves infiltrate dreams to steal secrets.', 8.7),
('The Lord of the Rings: The Two Towers', 2002, 'Battle for Rohan and quest to destroy the ring.', 8.7),
('Star Wars: Episode V - The Empire Strikes Back', 1980, 'Empire pursues the Rebels across the galaxy.', 8.7),
('The Matrix', 1999, 'A hacker discovers reality is a simulation.', 8.7),
('Goodfellas', 1990, 'Henry Hill rises in the mafia underworld.', 8.7),
('One Flew Over the Cuckoo''s Nest', 1975, 'A convict challenges oppressive asylum authority.', 8.7),
('Se7en', 1995, 'Detectives hunt a serial killer using seven deadly sins.', 8.6),
('Seven Samurai', 1954, 'Samurai defend a village from bandits.', 8.6),
('It''s a Wonderful Life', 1946, 'A guardian angel shows a man his worth.', 8.6),
('The Silence of the Lambs', 1991, 'Agent Clarice Starling consults Hannibal Lecter.', 8.6),
('City of God', 2002, 'Tale of crime and kids in Rio''s slums.', 8.6),
('Saving Private Ryan', 1998, 'Soldiers search for a paratrooper in WWII.', 8.6),
('Life Is Beautiful', 1997, 'Father uses humor to protect son in a camp.', 8.6),
('The Green Mile', 1999, 'Death row guard meets inmate with healing powers.', 8.6),
('Star Wars: Episode IV - A New Hope', 1977, 'Luke Skywalker joins Rebel Alliance.', 8.6),
('Interstellar', 2014, 'Astronauts travel through a wormhole seeking a new home.', 8.6),
('Terminator 2: Judgment Day', 1991, 'A cyborg protects a boy from a new terminator.', 8.5),
('Back to the Future', 1985, 'Teen travels back in time in a DeLorean.', 8.5),
('Psycho', 1960, 'A secretary encounters a disturbed motel owner.', 8.5),
('The Pianist', 2002, 'Jewish pianist survives WWII in Warsaw.', 8.5),
('The Lion King', 1994, 'Young lion prince flees, then reclaims his kingdom.', 8.5),
('Gladiator', 2000, 'A betrayed general seeks vengeance as a gladiator.', 8.5),
('American History X', 1998, 'A former neo-nazi tries to prevent his brother from following his path.', 8.5),
('The Departed', 2006, 'Undercover cop and mole engage in cat-and-mouse.', 8.5),
('Whiplash', 2014, 'A drummer endures tough mentorship at music conservatory.', 8.5),
('The Prestige', 2006, 'Two magicians feud with tragic consequences.', 8.5),
('The Usual Suspects', 1995, 'Criminals are interrogated about a mysterious boss.', 8.5),
('Raiders of the Lost Ark', 1981, 'Archaeologist Indiana Jones races Nazis for the Ark.', 8.4),
('Django Unchained', 2012, 'A freed slave sets out to rescue his wife.', 8.4),
('WALL·E', 2008, 'A robot cleans Earth and embarks on space journey.', 8.4),
('The Dark Knight Rises', 2012, 'Batman returns to face Bane in Gotham.', 8.4),
('Princess Mononoke', 1997, 'A warrior gets involved in conflict between gods and humans.', 8.4),
('Oldboy', 2003, 'A man seeks revenge after imprisonment for 15 years.', 8.4),
('Once Upon a Time in the West', 1968, 'A mysterious stranger joins forces to protect a widow.', 8.4),
('Aliens', 1986, 'Ripley returns to battle creatures on a colony.', 8.4),
('Avengers: Infinity War', 2018, 'Heroes unite to stop Thanos from gathering Infinity Stones.', 8.4),
('Avengers: Endgame', 2019, 'The Avengers attempt to reverse Thanos''s actions.', 8.4),
('The Great Dictator', 1940, 'A satirical comedy about a dictator and a barber.', 8.4),
('Memento', 2000, 'A man with short-term memory loss seeks vengeance.', 8.4),
('Apocalypse Now', 1979, 'A mission up river to terminate a rogue colonel.', 8.4),
('Your Name', 2016, 'Two teens swap bodies and search for each other.', 8.4),
('The Hunt', 2012, 'A man is falsely accused and ostracized by his community.', 8.3),
('Coco', 2017, 'Young boy journeys to the Land of the Dead.', 8.4),
('Amélie', 2001, 'A whimsical girl improves others'' lives in Paris.', 8.3),
('Braveheart', 1995, 'Scottish warrior leads an uprising against England.', 8.3),
('Das Boot', 1981, 'German U-boat crew endure WWII hardships.', 8.3),
('Reservoir Dogs', 1992, 'After a botched heist, gang suspects a rat.', 8.3),
('Citizen Kane', 1941, 'A publishing tycoon''s rise and fall.', 8.3),
('Vertigo', 1958, 'A detective with acrophobia becomes obsessed.', 8.3),
('Requiem for a Dream', 2000, 'Addiction destroys lives in different ways.', 8.3),
('North by Northwest', 1959, 'Man is chased by spies across America.', 8.3),
('M', 1931, 'A city hunts a child murderer.', 8.3),
('Indiana Jones and the Last Crusade', 1989, 'Indiana Jones and his father seek the Holy Grail.', 8.2),
('Double Indemnity', 1944, 'Insurance salesman plots murder with a housewife.', 8.3),
('Taxi Driver', 1976, 'A loner becomes a vigilante in NYC.', 8.3),
('Toy Story', 1995, 'Toys come to life when humans aren''t around.', 8.3),
('Logan', 2017, 'An aging Wolverine protects a mutant girl.', 8.1),
('Full Metal Jacket', 1987, 'Marines endure boot camp and Vietnam.', 8.3),
('Lawrence of Arabia', 1962, 'T.E. Lawrence unites Arab tribes during WWI.', 8.3),
('The Sting', 1973, 'Two con men plot revenge on a mob boss.', 8.3),
('Eternal Sunshine of the Spotless Mind', 2004, 'Couple erases each other from memory.', 8.3),
('Batman Begins', 2005, 'Bruce Wayne becomes Batman to fight crime.', 8.2),
('The Wolf of Wall Street', 2013, 'Stockbroker rises and falls in crime and greed.', 8.2),
('Gran Torino', 2008, 'A grumpy war veteran protects his neighbor.', 8.2),
('The Elephant Man', 1980, 'A severely deformed man in Victorian London.', 8.2),
('The Truman Show', 1998, 'A man discovers his life is a TV show.', 8.1),
('Pan''s Labyrinth', 2006, 'Girl in post-civil war Spain finds a fantasy world.', 8.2),
('The Great Escape', 1963, 'Allied POWs plan a mass escape from a camp.', 8.2),
('The Sixth Sense', 1999, 'A boy sees dead people; a psychologist helps him.', 8.1),
('A Clockwork Orange', 1971, 'A violent delinquent undergoes behavior modification.', 8.3),
('Howl''s Moving Castle', 2004, 'A young woman cursed by a witch seeks help.', 8.2),
('Tenet', 2020, 'A CIA operative is recruited into a secret organization called Tenet and must prevent World War III through time-inversion technology.', 7.3),
('The Trial of the Chicago 7', 2020, 'Aaron Sorkin''s dramatization of the 1969 trial of anti-Vietnam War protestors charged with conspiracy and inciting riots at the DNC.', 7.7),
('Soul', 2020, 'Pixar''s animated tale of a jazz musician whose soul gets separated from his body and must rediscover what makes life worth living.',  7.6),
('Dune', 2021, 'Denis Villeneuve''s epic adaptation following Paul Atreides as his noble family battles for control of the desert planet Arrakis.', 8.0),
('No Time to Die', 2021, 'Daniel Craig''s final outing as James Bond, who is drawn back into action to rescue a kidnapped scientist and confront a vengeful villain.', 6.8),
('Spider-Man: No Way Home', 2021, 'Peter Parker enlists Doctor Strange''s help to erase his identity—a spell that fractures the multiverse and brings foes and other Spider-Men into his world.', 9.4),
('Top Gun: Maverick', 2022, 'Tom Cruise returns as Maverick, now charged with training a new generation of Top Gun pilots for a critical, high-stakes mission.', 9.7),
('Everything Everywhere All at Once', 2022, 'An overwhelmed laundromat owner is swept into an absurd multiverse adventure where she must connect with countless versions of herself to save reality.', 8.6),
('Avatar: The Way of Water', 2022, 'Jake Sully and his family seek refuge among the aquatic Metkayina clan on Pandora, facing new human threats and breathtaking underwater worlds.', 7.1),
('Oppenheimer', 2023, 'Christopher Nolan''s biographical drama chronicling J. Robert Oppenheimer''s role in the development of the atomic bomb and its moral fallout.', 8.6),
('Barbie', 2023, 'Greta Gerwig''s live-action comedy following Barbie and Ken as they embark on a journey of self-discovery in both Barbieland and the real world.', 7.3),
('Mission: Impossible - Dead Reckoning Part One', 2023, 'Ethan Hunt faces a rogue AI superweapon called "The Entity" in the penultimate Mission: Impossible installment, racing against time to save the world.', 9.4),
('Dune: Part Two', 2024, 'The saga continues as Paul Atreides seeks revenge and the prophesied transformation of Arrakis looms, pitting him against renewed Harkonnen threats.', 8.1),
('Furiosa: A Mad Max Saga', 2024, 'A prequel to Mad Max: Fury Road, following the origins of Imperator Furiosa and her fight for survival in a desert wasteland.', 7.6),
('A Quiet Place: Day One', 2024, 'The origin story of the deadly creatures'' first invasion of Earth, seen through the eyes of a young woman trying to reach safety in New York City.', 7.1),
('Fast X', 2024, 'Dom Toretto and his family face a new threat from Dante Reyes, seeking vengeance for the death of his father against the Fast team.', 7.0),
('Kingdom of the Planet of the Apes', 2025, 'Generations after Caesar''s reign, a young ape named Noa embarks on a journey that will determine a future for apes and humans alike.', 8.0);
